#!/usr/bin/env python
# coding: utf-8

import os
import {{ app|lower }}

from docopt import docopt
from {{ module }}.cli import Cli

doc = """{{ app|title }}, ## Set description.

Usage:
  {{ app|lower }} -h | --help
  {{ app|lower }} -v | --version

Options:
  -h --help           Show help
  -v --version        Show version
"""

if __name__ == '__main__':
	args = docopt(doc, version={{ app|lower }}.__version__)
	cli = Cli(**args)
	cli.start()
